spring.application.name=springjwtexample
# DATABASE SETTINGS
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_app_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.flyway.driver-class-name=postgresql
JWT_SECRET_KEY=JbKOPrarEtvcb5/AUmYVNsxy7OEy7qN0sKlLzfJCfC8=